/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChildrenIndexRouteImport } from './routes/children/index'
import { Route as ChildrenHihiRouteImport } from './routes/children/hihi'
import { Route as ChildrenIdIndexRouteImport } from './routes/children/$id/index'
import { Route as ChildrenIdDetailRouteImport } from './routes/children/$id/detail'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenIndexRoute = ChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenHihiRoute = ChildrenHihiRouteImport.update({
  id: '/children/hihi',
  path: '/children/hihi',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenIdIndexRoute = ChildrenIdIndexRouteImport.update({
  id: '/children/$id/',
  path: '/children/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenIdDetailRoute = ChildrenIdDetailRouteImport.update({
  id: '/children/$id/detail',
  path: '/children/$id/detail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/children/hihi': typeof ChildrenHihiRoute
  '/children': typeof ChildrenIndexRoute
  '/children/$id/detail': typeof ChildrenIdDetailRoute
  '/children/$id': typeof ChildrenIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/children/hihi': typeof ChildrenHihiRoute
  '/children': typeof ChildrenIndexRoute
  '/children/$id/detail': typeof ChildrenIdDetailRoute
  '/children/$id': typeof ChildrenIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/children/hihi': typeof ChildrenHihiRoute
  '/children/': typeof ChildrenIndexRoute
  '/children/$id/detail': typeof ChildrenIdDetailRoute
  '/children/$id/': typeof ChildrenIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/children/hihi'
    | '/children'
    | '/children/$id/detail'
    | '/children/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/children/hihi'
    | '/children'
    | '/children/$id/detail'
    | '/children/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/children/hihi'
    | '/children/'
    | '/children/$id/detail'
    | '/children/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ChildrenHihiRoute: typeof ChildrenHihiRoute
  ChildrenIndexRoute: typeof ChildrenIndexRoute
  ChildrenIdDetailRoute: typeof ChildrenIdDetailRoute
  ChildrenIdIndexRoute: typeof ChildrenIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/': {
      id: '/children/'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof ChildrenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/hihi': {
      id: '/children/hihi'
      path: '/children/hihi'
      fullPath: '/children/hihi'
      preLoaderRoute: typeof ChildrenHihiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$id/': {
      id: '/children/$id/'
      path: '/children/$id'
      fullPath: '/children/$id'
      preLoaderRoute: typeof ChildrenIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$id/detail': {
      id: '/children/$id/detail'
      path: '/children/$id/detail'
      fullPath: '/children/$id/detail'
      preLoaderRoute: typeof ChildrenIdDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ChildrenHihiRoute: ChildrenHihiRoute,
  ChildrenIndexRoute: ChildrenIndexRoute,
  ChildrenIdDetailRoute: ChildrenIdDetailRoute,
  ChildrenIdIndexRoute: ChildrenIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
